// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/tsm/v1/tsm.proto

package tsmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SessionStatus 對應 tmux.SessionStatus。
type SessionStatus int32

const (
	SessionStatus_SESSION_STATUS_IDLE    SessionStatus = 0
	SessionStatus_SESSION_STATUS_RUNNING SessionStatus = 1
	SessionStatus_SESSION_STATUS_WAITING SessionStatus = 2
	SessionStatus_SESSION_STATUS_ERROR   SessionStatus = 3
)

// Enum value maps for SessionStatus.
var (
	SessionStatus_name = map[int32]string{
		0: "SESSION_STATUS_IDLE",
		1: "SESSION_STATUS_RUNNING",
		2: "SESSION_STATUS_WAITING",
		3: "SESSION_STATUS_ERROR",
	}
	SessionStatus_value = map[string]int32{
		"SESSION_STATUS_IDLE":    0,
		"SESSION_STATUS_RUNNING": 1,
		"SESSION_STATUS_WAITING": 2,
		"SESSION_STATUS_ERROR":   3,
	}
)

func (x SessionStatus) Enum() *SessionStatus {
	p := new(SessionStatus)
	*p = x
	return p
}

func (x SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_tsm_v1_tsm_proto_enumTypes[0].Descriptor()
}

func (SessionStatus) Type() protoreflect.EnumType {
	return &file_api_proto_tsm_v1_tsm_proto_enumTypes[0]
}

func (x SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionStatus.Descriptor instead.
func (SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{0}
}

// HostStatus 描述主機連線狀態。
type HostStatus int32

const (
	HostStatus_HOST_STATUS_DISABLED     HostStatus = 0
	HostStatus_HOST_STATUS_CONNECTING   HostStatus = 1
	HostStatus_HOST_STATUS_CONNECTED    HostStatus = 2
	HostStatus_HOST_STATUS_DISCONNECTED HostStatus = 3
)

// Enum value maps for HostStatus.
var (
	HostStatus_name = map[int32]string{
		0: "HOST_STATUS_DISABLED",
		1: "HOST_STATUS_CONNECTING",
		2: "HOST_STATUS_CONNECTED",
		3: "HOST_STATUS_DISCONNECTED",
	}
	HostStatus_value = map[string]int32{
		"HOST_STATUS_DISABLED":     0,
		"HOST_STATUS_CONNECTING":   1,
		"HOST_STATUS_CONNECTED":    2,
		"HOST_STATUS_DISCONNECTED": 3,
	}
)

func (x HostStatus) Enum() *HostStatus {
	p := new(HostStatus)
	*p = x
	return p
}

func (x HostStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HostStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_tsm_v1_tsm_proto_enumTypes[1].Descriptor()
}

func (HostStatus) Type() protoreflect.EnumType {
	return &file_api_proto_tsm_v1_tsm_proto_enumTypes[1]
}

func (x HostStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HostStatus.Descriptor instead.
func (HostStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{1}
}

// MutationType 列舉所有可被代理的操作類型。
type MutationType int32

const (
	MutationType_MUTATION_KILL_SESSION   MutationType = 0
	MutationType_MUTATION_RENAME_SESSION MutationType = 1
	MutationType_MUTATION_CREATE_SESSION MutationType = 2
	MutationType_MUTATION_MOVE_SESSION   MutationType = 3
)

// Enum value maps for MutationType.
var (
	MutationType_name = map[int32]string{
		0: "MUTATION_KILL_SESSION",
		1: "MUTATION_RENAME_SESSION",
		2: "MUTATION_CREATE_SESSION",
		3: "MUTATION_MOVE_SESSION",
	}
	MutationType_value = map[string]int32{
		"MUTATION_KILL_SESSION":   0,
		"MUTATION_RENAME_SESSION": 1,
		"MUTATION_CREATE_SESSION": 2,
		"MUTATION_MOVE_SESSION":   3,
	}
)

func (x MutationType) Enum() *MutationType {
	p := new(MutationType)
	*p = x
	return p
}

func (x MutationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MutationType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_tsm_v1_tsm_proto_enumTypes[2].Descriptor()
}

func (MutationType) Type() protoreflect.EnumType {
	return &file_api_proto_tsm_v1_tsm_proto_enumTypes[2]
}

func (x MutationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MutationType.Descriptor instead.
func (MutationType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{2}
}

// Session 對應 tmux.Session。
type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Attached      bool                   `protobuf:"varint,4,opt,name=attached,proto3" json:"attached,omitempty"`
	Activity      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=activity,proto3" json:"activity,omitempty"`
	Status        SessionStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=tsm.v1.SessionStatus" json:"status,omitempty"`
	AiModel       string                 `protobuf:"bytes,7,opt,name=ai_model,json=aiModel,proto3" json:"ai_model,omitempty"`
	AiSummary     string                 `protobuf:"bytes,8,opt,name=ai_summary,json=aiSummary,proto3" json:"ai_summary,omitempty"`
	GroupName     string                 `protobuf:"bytes,9,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	SortOrder     int32                  `protobuf:"varint,10,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	CustomName    string                 `protobuf:"bytes,11,opt,name=custom_name,json=customName,proto3" json:"custom_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Session) GetAttached() bool {
	if x != nil {
		return x.Attached
	}
	return false
}

func (x *Session) GetActivity() *timestamppb.Timestamp {
	if x != nil {
		return x.Activity
	}
	return nil
}

func (x *Session) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_IDLE
}

func (x *Session) GetAiModel() string {
	if x != nil {
		return x.AiModel
	}
	return ""
}

func (x *Session) GetAiSummary() string {
	if x != nil {
		return x.AiSummary
	}
	return ""
}

func (x *Session) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *Session) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Session) GetCustomName() string {
	if x != nil {
		return x.CustomName
	}
	return ""
}

// Group 對應 store.Group。
type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SortOrder     int32                  `protobuf:"varint,3,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Collapsed     bool                   `protobuf:"varint,4,opt,name=collapsed,proto3" json:"collapsed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{1}
}

func (x *Group) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Group) GetCollapsed() bool {
	if x != nil {
		return x.Collapsed
	}
	return false
}

// StateSnapshot 是 Watch stream 推送的全量快照。
type StateSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Groups        []*Group               `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	UploadEvents  []*UploadEvent         `protobuf:"bytes,3,rep,name=upload_events,json=uploadEvents,proto3" json:"upload_events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateSnapshot) Reset() {
	*x = StateSnapshot{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSnapshot) ProtoMessage() {}

func (x *StateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSnapshot.ProtoReflect.Descriptor instead.
func (*StateSnapshot) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{2}
}

func (x *StateSnapshot) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *StateSnapshot) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *StateSnapshot) GetUploadEvents() []*UploadEvent {
	if x != nil {
		return x.UploadEvents
	}
	return nil
}

// HostState 描述一台主機的連線狀態與快照。
type HostState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Status        HostStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=tsm.v1.HostStatus" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Snapshot      *StateSnapshot         `protobuf:"bytes,6,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostState) Reset() {
	*x = HostState{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostState) ProtoMessage() {}

func (x *HostState) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostState.ProtoReflect.Descriptor instead.
func (*HostState) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{3}
}

func (x *HostState) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *HostState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HostState) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *HostState) GetStatus() HostStatus {
	if x != nil {
		return x.Status
	}
	return HostStatus_HOST_STATUS_DISABLED
}

func (x *HostState) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *HostState) GetSnapshot() *StateSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

// MultiHostSnapshot 聚合所有主機的狀態快照。
type MultiHostSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         []*HostState           `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiHostSnapshot) Reset() {
	*x = MultiHostSnapshot{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiHostSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiHostSnapshot) ProtoMessage() {}

func (x *MultiHostSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiHostSnapshot.ProtoReflect.Descriptor instead.
func (*MultiHostSnapshot) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{4}
}

func (x *MultiHostSnapshot) GetHosts() []*HostState {
	if x != nil {
		return x.Hosts
	}
	return nil
}

// ProxyMutationRequest 由遠端 TUI 發送，透過 hub 代理到目標主機。
type ProxyMutationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Type          MutationType           `protobuf:"varint,2,opt,name=type,proto3,enum=tsm.v1.MutationType" json:"type,omitempty"`
	SessionName   string                 `protobuf:"bytes,3,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	NewName       string                 `protobuf:"bytes,4,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	GroupId       string                 `protobuf:"bytes,5,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyMutationRequest) Reset() {
	*x = ProxyMutationRequest{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyMutationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyMutationRequest) ProtoMessage() {}

func (x *ProxyMutationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyMutationRequest.ProtoReflect.Descriptor instead.
func (*ProxyMutationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{5}
}

func (x *ProxyMutationRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *ProxyMutationRequest) GetType() MutationType {
	if x != nil {
		return x.Type
	}
	return MutationType_MUTATION_KILL_SESSION
}

func (x *ProxyMutationRequest) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

func (x *ProxyMutationRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

func (x *ProxyMutationRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

// ProxyMutationResponse 代理操作結果。
type ProxyMutationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyMutationResponse) Reset() {
	*x = ProxyMutationResponse{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyMutationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyMutationResponse) ProtoMessage() {}

func (x *ProxyMutationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyMutationResponse.ProtoReflect.Descriptor instead.
func (*ProxyMutationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{6}
}

func (x *ProxyMutationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProxyMutationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// WatchRequest 是 Watch RPC 的請求（目前為空，未來可擴充過濾條件）。
type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{7}
}

// WatchMultiHostRequest 是 WatchMultiHost RPC 的請求（hub 模式專用）。
type WatchMultiHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchMultiHostRequest) Reset() {
	*x = WatchMultiHostRequest{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchMultiHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchMultiHostRequest) ProtoMessage() {}

func (x *WatchMultiHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchMultiHostRequest.ProtoReflect.Descriptor instead.
func (*WatchMultiHostRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{8}
}

// CreateSessionRequest 建立新的 tmux session。
type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"` // agent 啟動指令（空字串=純 shell）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{9}
}

func (x *CreateSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSessionRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateSessionRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

// KillSessionRequest 刪除指定的 tmux session。
type KillSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillSessionRequest) Reset() {
	*x = KillSessionRequest{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillSessionRequest) ProtoMessage() {}

func (x *KillSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillSessionRequest.ProtoReflect.Descriptor instead.
func (*KillSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{10}
}

func (x *KillSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// RenameSessionRequest 設定 session 的自訂顯示名稱，並可選擇重命名 tmux session。
type RenameSessionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionName    string                 `protobuf:"bytes,1,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	CustomName     string                 `protobuf:"bytes,2,opt,name=custom_name,json=customName,proto3" json:"custom_name,omitempty"`
	NewSessionName string                 `protobuf:"bytes,3,opt,name=new_session_name,json=newSessionName,proto3" json:"new_session_name,omitempty"` // 重命名 tmux session（空 = 不變）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RenameSessionRequest) Reset() {
	*x = RenameSessionRequest{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameSessionRequest) ProtoMessage() {}

func (x *RenameSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameSessionRequest.ProtoReflect.Descriptor instead.
func (*RenameSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{11}
}

func (x *RenameSessionRequest) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

func (x *RenameSessionRequest) GetCustomName() string {
	if x != nil {
		return x.CustomName
	}
	return ""
}

func (x *RenameSessionRequest) GetNewSessionName() string {
	if x != nil {
		return x.NewSessionName
	}
	return ""
}

// RenameGroupRequest 重命名群組。
type RenameGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	NewName       string                 `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameGroupRequest) Reset() {
	*x = RenameGroupRequest{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameGroupRequest) ProtoMessage() {}

func (x *RenameGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameGroupRequest.ProtoReflect.Descriptor instead.
func (*RenameGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{12}
}

func (x *RenameGroupRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *RenameGroupRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

// CreateGroupRequest 建立新的群組。
type CreateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SortOrder     int32                  `protobuf:"varint,2,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{13}
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

// MoveSessionRequest 將 session 移動到指定群組。
type MoveSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionName   string                 `protobuf:"bytes,1,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	SortOrder     int32                  `protobuf:"varint,3,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveSessionRequest) Reset() {
	*x = MoveSessionRequest{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveSessionRequest) ProtoMessage() {}

func (x *MoveSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveSessionRequest.ProtoReflect.Descriptor instead.
func (*MoveSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{14}
}

func (x *MoveSessionRequest) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

func (x *MoveSessionRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *MoveSessionRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

// ReorderRequest 重新排序群組或群組內的 session。
type ReorderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 被排序的對象類型
	//
	// Types that are valid to be assigned to Target:
	//
	//	*ReorderRequest_Group
	//	*ReorderRequest_Session
	Target        isReorderRequest_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderRequest) Reset() {
	*x = ReorderRequest{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderRequest) ProtoMessage() {}

func (x *ReorderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderRequest.ProtoReflect.Descriptor instead.
func (*ReorderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{15}
}

func (x *ReorderRequest) GetTarget() isReorderRequest_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ReorderRequest) GetGroup() *GroupReorder {
	if x != nil {
		if x, ok := x.Target.(*ReorderRequest_Group); ok {
			return x.Group
		}
	}
	return nil
}

func (x *ReorderRequest) GetSession() *SessionReorder {
	if x != nil {
		if x, ok := x.Target.(*ReorderRequest_Session); ok {
			return x.Session
		}
	}
	return nil
}

type isReorderRequest_Target interface {
	isReorderRequest_Target()
}

type ReorderRequest_Group struct {
	Group *GroupReorder `protobuf:"bytes,1,opt,name=group,proto3,oneof"`
}

type ReorderRequest_Session struct {
	Session *SessionReorder `protobuf:"bytes,2,opt,name=session,proto3,oneof"`
}

func (*ReorderRequest_Group) isReorderRequest_Target() {}

func (*ReorderRequest_Session) isReorderRequest_Target() {}

type GroupReorder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	NewSortOrder  int32                  `protobuf:"varint,2,opt,name=new_sort_order,json=newSortOrder,proto3" json:"new_sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupReorder) Reset() {
	*x = GroupReorder{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupReorder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupReorder) ProtoMessage() {}

func (x *GroupReorder) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupReorder.ProtoReflect.Descriptor instead.
func (*GroupReorder) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{16}
}

func (x *GroupReorder) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupReorder) GetNewSortOrder() int32 {
	if x != nil {
		return x.NewSortOrder
	}
	return 0
}

type SessionReorder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionName   string                 `protobuf:"bytes,1,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	NewSortOrder  int32                  `protobuf:"varint,3,opt,name=new_sort_order,json=newSortOrder,proto3" json:"new_sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionReorder) Reset() {
	*x = SessionReorder{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionReorder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionReorder) ProtoMessage() {}

func (x *SessionReorder) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionReorder.ProtoReflect.Descriptor instead.
func (*SessionReorder) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{17}
}

func (x *SessionReorder) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

func (x *SessionReorder) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *SessionReorder) GetNewSortOrder() int32 {
	if x != nil {
		return x.NewSortOrder
	}
	return 0
}

// ToggleCollapseRequest 切換群組的展開/收合狀態。
type ToggleCollapseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleCollapseRequest) Reset() {
	*x = ToggleCollapseRequest{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleCollapseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleCollapseRequest) ProtoMessage() {}

func (x *ToggleCollapseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleCollapseRequest.ProtoReflect.Descriptor instead.
func (*ToggleCollapseRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{18}
}

func (x *ToggleCollapseRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// DaemonStatusResponse 回傳 daemon 的狀態資訊。
type DaemonStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	WatcherCount  int32                  `protobuf:"varint,3,opt,name=watcher_count,json=watcherCount,proto3" json:"watcher_count,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonStatusResponse) Reset() {
	*x = DaemonStatusResponse{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonStatusResponse) ProtoMessage() {}

func (x *DaemonStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonStatusResponse.ProtoReflect.Descriptor instead.
func (*DaemonStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{19}
}

func (x *DaemonStatusResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *DaemonStatusResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *DaemonStatusResponse) GetWatcherCount() int32 {
	if x != nil {
		return x.WatcherCount
	}
	return 0
}

func (x *DaemonStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// ConfigValue 代表一個設定鍵值對。
type ConfigValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigValue) Reset() {
	*x = ConfigValue{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigValue) ProtoMessage() {}

func (x *ConfigValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigValue.ProtoReflect.Descriptor instead.
func (*ConfigValue) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{20}
}

func (x *ConfigValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// GetConfigRequest 取得設定。
type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{21}
}

// GetConfigResponse 回傳設定值。
type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*ConfigValue         `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{22}
}

func (x *GetConfigResponse) GetValues() []*ConfigValue {
	if x != nil {
		return x.Values
	}
	return nil
}

// SetConfigRequest 設定值（可一次設定多個）。
type SetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*ConfigValue         `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigRequest) Reset() {
	*x = SetConfigRequest{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigRequest) ProtoMessage() {}

func (x *SetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigRequest.ProtoReflect.Descriptor instead.
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{23}
}

func (x *SetConfigRequest) GetValues() []*ConfigValue {
	if x != nil {
		return x.Values
	}
	return nil
}

// UploadedFile 代表一個已上傳的檔案。
type UploadedFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalPath     string                 `protobuf:"bytes,1,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	RemotePath    string                 `protobuf:"bytes,2,opt,name=remote_path,json=remotePath,proto3" json:"remote_path,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadedFile) Reset() {
	*x = UploadedFile{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadedFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadedFile) ProtoMessage() {}

func (x *UploadedFile) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadedFile.ProtoReflect.Descriptor instead.
func (*UploadedFile) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{24}
}

func (x *UploadedFile) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

func (x *UploadedFile) GetRemotePath() string {
	if x != nil {
		return x.RemotePath
	}
	return ""
}

func (x *UploadedFile) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

// UploadEvent 代表一次上傳事件的結果。
type UploadEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*UploadedFile        `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadEvent) Reset() {
	*x = UploadEvent{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadEvent) ProtoMessage() {}

func (x *UploadEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadEvent.ProtoReflect.Descriptor instead.
func (*UploadEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{25}
}

func (x *UploadEvent) GetFiles() []*UploadedFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *UploadEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UploadEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// GetUploadTargetRequest 查詢當前 focused session 的上傳目標資訊。
type GetUploadTargetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadTargetRequest) Reset() {
	*x = GetUploadTargetRequest{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadTargetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadTargetRequest) ProtoMessage() {}

func (x *GetUploadTargetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadTargetRequest.ProtoReflect.Descriptor instead.
func (*GetUploadTargetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{26}
}

// GetUploadTargetResponse 回傳上傳目標判斷結果。
type GetUploadTargetResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UploadMode     bool                   `protobuf:"varint,1,opt,name=upload_mode,json=uploadMode,proto3" json:"upload_mode,omitempty"`
	IsRemote       bool                   `protobuf:"varint,2,opt,name=is_remote,json=isRemote,proto3" json:"is_remote,omitempty"`
	IsClaudeActive bool                   `protobuf:"varint,3,opt,name=is_claude_active,json=isClaudeActive,proto3" json:"is_claude_active,omitempty"`
	SshTarget      string                 `protobuf:"bytes,4,opt,name=ssh_target,json=sshTarget,proto3" json:"ssh_target,omitempty"`
	SshPort        int32                  `protobuf:"varint,5,opt,name=ssh_port,json=sshPort,proto3" json:"ssh_port,omitempty"`
	UploadPath     string                 `protobuf:"bytes,6,opt,name=upload_path,json=uploadPath,proto3" json:"upload_path,omitempty"`
	SessionName    string                 `protobuf:"bytes,7,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUploadTargetResponse) Reset() {
	*x = GetUploadTargetResponse{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadTargetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadTargetResponse) ProtoMessage() {}

func (x *GetUploadTargetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadTargetResponse.ProtoReflect.Descriptor instead.
func (*GetUploadTargetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{27}
}

func (x *GetUploadTargetResponse) GetUploadMode() bool {
	if x != nil {
		return x.UploadMode
	}
	return false
}

func (x *GetUploadTargetResponse) GetIsRemote() bool {
	if x != nil {
		return x.IsRemote
	}
	return false
}

func (x *GetUploadTargetResponse) GetIsClaudeActive() bool {
	if x != nil {
		return x.IsClaudeActive
	}
	return false
}

func (x *GetUploadTargetResponse) GetSshTarget() string {
	if x != nil {
		return x.SshTarget
	}
	return ""
}

func (x *GetUploadTargetResponse) GetSshPort() int32 {
	if x != nil {
		return x.SshPort
	}
	return 0
}

func (x *GetUploadTargetResponse) GetUploadPath() string {
	if x != nil {
		return x.UploadPath
	}
	return ""
}

func (x *GetUploadTargetResponse) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

// SetUploadModeRequest 設定上傳模式開關。
type SetUploadModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	SessionName   string                 `protobuf:"bytes,2,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUploadModeRequest) Reset() {
	*x = SetUploadModeRequest{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUploadModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUploadModeRequest) ProtoMessage() {}

func (x *SetUploadModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUploadModeRequest.ProtoReflect.Descriptor instead.
func (*SetUploadModeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{28}
}

func (x *SetUploadModeRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SetUploadModeRequest) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

// ReportUploadResultRequest 回報上傳結果。
type ReportUploadResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionName   string                 `protobuf:"bytes,1,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	Files         []*UploadedFile        `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportUploadResultRequest) Reset() {
	*x = ReportUploadResultRequest{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportUploadResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportUploadResultRequest) ProtoMessage() {}

func (x *ReportUploadResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportUploadResultRequest.ProtoReflect.Descriptor instead.
func (*ReportUploadResultRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{29}
}

func (x *ReportUploadResultRequest) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

func (x *ReportUploadResultRequest) GetFiles() []*UploadedFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ReportUploadResultRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_proto_tsm_v1_tsm_proto protoreflect.FileDescriptor

const file_api_proto_tsm_v1_tsm_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/tsm/v1/tsm.proto\x12\x06tsm.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdd\x02\n" +
	"\aSession\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1a\n" +
	"\battached\x18\x04 \x01(\bR\battached\x126\n" +
	"\bactivity\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bactivity\x12-\n" +
	"\x06status\x18\x06 \x01(\x0e2\x15.tsm.v1.SessionStatusR\x06status\x12\x19\n" +
	"\bai_model\x18\a \x01(\tR\aaiModel\x12\x1d\n" +
	"\n" +
	"ai_summary\x18\b \x01(\tR\taiSummary\x12\x1d\n" +
	"\n" +
	"group_name\x18\t \x01(\tR\tgroupName\x12\x1d\n" +
	"\n" +
	"sort_order\x18\n" +
	" \x01(\x05R\tsortOrder\x12\x1f\n" +
	"\vcustom_name\x18\v \x01(\tR\n" +
	"customName\"h\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x03 \x01(\x05R\tsortOrder\x12\x1c\n" +
	"\tcollapsed\x18\x04 \x01(\bR\tcollapsed\"\x9d\x01\n" +
	"\rStateSnapshot\x12+\n" +
	"\bsessions\x18\x01 \x03(\v2\x0f.tsm.v1.SessionR\bsessions\x12%\n" +
	"\x06groups\x18\x02 \x03(\v2\r.tsm.v1.GroupR\x06groups\x128\n" +
	"\rupload_events\x18\x03 \x03(\v2\x13.tsm.v1.UploadEventR\fuploadEvents\"\xc3\x01\n" +
	"\tHostState\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12*\n" +
	"\x06status\x18\x04 \x01(\x0e2\x12.tsm.v1.HostStatusR\x06status\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x121\n" +
	"\bsnapshot\x18\x06 \x01(\v2\x15.tsm.v1.StateSnapshotR\bsnapshot\"<\n" +
	"\x11MultiHostSnapshot\x12'\n" +
	"\x05hosts\x18\x01 \x03(\v2\x11.tsm.v1.HostStateR\x05hosts\"\xb2\x01\n" +
	"\x14ProxyMutationRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12(\n" +
	"\x04type\x18\x02 \x01(\x0e2\x14.tsm.v1.MutationTypeR\x04type\x12!\n" +
	"\fsession_name\x18\x03 \x01(\tR\vsessionName\x12\x19\n" +
	"\bnew_name\x18\x04 \x01(\tR\anewName\x12\x19\n" +
	"\bgroup_id\x18\x05 \x01(\tR\agroupId\"G\n" +
	"\x15ProxyMutationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x0e\n" +
	"\fWatchRequest\"\x17\n" +
	"\x15WatchMultiHostRequest\"X\n" +
	"\x14CreateSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\"(\n" +
	"\x12KillSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x84\x01\n" +
	"\x14RenameSessionRequest\x12!\n" +
	"\fsession_name\x18\x01 \x01(\tR\vsessionName\x12\x1f\n" +
	"\vcustom_name\x18\x02 \x01(\tR\n" +
	"customName\x12(\n" +
	"\x10new_session_name\x18\x03 \x01(\tR\x0enewSessionName\"J\n" +
	"\x12RenameGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x19\n" +
	"\bnew_name\x18\x02 \x01(\tR\anewName\"G\n" +
	"\x12CreateGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x02 \x01(\x05R\tsortOrder\"q\n" +
	"\x12MoveSessionRequest\x12!\n" +
	"\fsession_name\x18\x01 \x01(\tR\vsessionName\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x03 \x01(\x05R\tsortOrder\"|\n" +
	"\x0eReorderRequest\x12,\n" +
	"\x05group\x18\x01 \x01(\v2\x14.tsm.v1.GroupReorderH\x00R\x05group\x122\n" +
	"\asession\x18\x02 \x01(\v2\x16.tsm.v1.SessionReorderH\x00R\asessionB\b\n" +
	"\x06target\"O\n" +
	"\fGroupReorder\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12$\n" +
	"\x0enew_sort_order\x18\x02 \x01(\x05R\fnewSortOrder\"t\n" +
	"\x0eSessionReorder\x12!\n" +
	"\fsession_name\x18\x01 \x01(\tR\vsessionName\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\x12$\n" +
	"\x0enew_sort_order\x18\x03 \x01(\x05R\fnewSortOrder\"2\n" +
	"\x15ToggleCollapseRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\"\xa2\x01\n" +
	"\x14DaemonStatusResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x129\n" +
	"\n" +
	"started_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12#\n" +
	"\rwatcher_count\x18\x03 \x01(\x05R\fwatcherCount\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"5\n" +
	"\vConfigValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x12\n" +
	"\x10GetConfigRequest\"@\n" +
	"\x11GetConfigResponse\x12+\n" +
	"\x06values\x18\x01 \x03(\v2\x13.tsm.v1.ConfigValueR\x06values\"?\n" +
	"\x10SetConfigRequest\x12+\n" +
	"\x06values\x18\x01 \x03(\v2\x13.tsm.v1.ConfigValueR\x06values\"m\n" +
	"\fUploadedFile\x12\x1d\n" +
	"\n" +
	"local_path\x18\x01 \x01(\tR\tlocalPath\x12\x1f\n" +
	"\vremote_path\x18\x02 \x01(\tR\n" +
	"remotePath\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\"m\n" +
	"\vUploadEvent\x12*\n" +
	"\x05files\x18\x01 \x03(\v2\x14.tsm.v1.UploadedFileR\x05files\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x18\n" +
	"\x16GetUploadTargetRequest\"\xff\x01\n" +
	"\x17GetUploadTargetResponse\x12\x1f\n" +
	"\vupload_mode\x18\x01 \x01(\bR\n" +
	"uploadMode\x12\x1b\n" +
	"\tis_remote\x18\x02 \x01(\bR\bisRemote\x12(\n" +
	"\x10is_claude_active\x18\x03 \x01(\bR\x0eisClaudeActive\x12\x1d\n" +
	"\n" +
	"ssh_target\x18\x04 \x01(\tR\tsshTarget\x12\x19\n" +
	"\bssh_port\x18\x05 \x01(\x05R\asshPort\x12\x1f\n" +
	"\vupload_path\x18\x06 \x01(\tR\n" +
	"uploadPath\x12!\n" +
	"\fsession_name\x18\a \x01(\tR\vsessionName\"S\n" +
	"\x14SetUploadModeRequest\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12!\n" +
	"\fsession_name\x18\x02 \x01(\tR\vsessionName\"\x80\x01\n" +
	"\x19ReportUploadResultRequest\x12!\n" +
	"\fsession_name\x18\x01 \x01(\tR\vsessionName\x12*\n" +
	"\x05files\x18\x02 \x03(\v2\x14.tsm.v1.UploadedFileR\x05files\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error*z\n" +
	"\rSessionStatus\x12\x17\n" +
	"\x13SESSION_STATUS_IDLE\x10\x00\x12\x1a\n" +
	"\x16SESSION_STATUS_RUNNING\x10\x01\x12\x1a\n" +
	"\x16SESSION_STATUS_WAITING\x10\x02\x12\x18\n" +
	"\x14SESSION_STATUS_ERROR\x10\x03*{\n" +
	"\n" +
	"HostStatus\x12\x18\n" +
	"\x14HOST_STATUS_DISABLED\x10\x00\x12\x1a\n" +
	"\x16HOST_STATUS_CONNECTING\x10\x01\x12\x19\n" +
	"\x15HOST_STATUS_CONNECTED\x10\x02\x12\x1c\n" +
	"\x18HOST_STATUS_DISCONNECTED\x10\x03*~\n" +
	"\fMutationType\x12\x19\n" +
	"\x15MUTATION_KILL_SESSION\x10\x00\x12\x1b\n" +
	"\x17MUTATION_RENAME_SESSION\x10\x01\x12\x1b\n" +
	"\x17MUTATION_CREATE_SESSION\x10\x02\x12\x19\n" +
	"\x15MUTATION_MOVE_SESSION\x10\x032\xb5\t\n" +
	"\x0eSessionManager\x126\n" +
	"\x05Watch\x12\x14.tsm.v1.WatchRequest\x1a\x15.tsm.v1.StateSnapshot0\x01\x12E\n" +
	"\rCreateSession\x12\x1c.tsm.v1.CreateSessionRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\vKillSession\x12\x1a.tsm.v1.KillSessionRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\rRenameSession\x12\x1c.tsm.v1.RenameSessionRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\vCreateGroup\x12\x1a.tsm.v1.CreateGroupRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\vRenameGroup\x12\x1a.tsm.v1.RenameGroupRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\vMoveSession\x12\x1a.tsm.v1.MoveSessionRequest\x1a\x16.google.protobuf.Empty\x129\n" +
	"\aReorder\x12\x16.tsm.v1.ReorderRequest\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\x0eToggleCollapse\x12\x1d.tsm.v1.ToggleCollapseRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\fDaemonStatus\x12\x16.google.protobuf.Empty\x1a\x1c.tsm.v1.DaemonStatusResponse\x12@\n" +
	"\tGetConfig\x12\x18.tsm.v1.GetConfigRequest\x1a\x19.tsm.v1.GetConfigResponse\x12=\n" +
	"\tSetConfig\x12\x18.tsm.v1.SetConfigRequest\x1a\x16.google.protobuf.Empty\x12R\n" +
	"\x0fGetUploadTarget\x12\x1e.tsm.v1.GetUploadTargetRequest\x1a\x1f.tsm.v1.GetUploadTargetResponse\x12E\n" +
	"\rSetUploadMode\x12\x1c.tsm.v1.SetUploadModeRequest\x1a\x16.google.protobuf.Empty\x12O\n" +
	"\x12ReportUploadResult\x12!.tsm.v1.ReportUploadResultRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\x0eWatchMultiHost\x12\x1d.tsm.v1.WatchMultiHostRequest\x1a\x19.tsm.v1.MultiHostSnapshot0\x01\x12L\n" +
	"\rProxyMutation\x12\x1c.tsm.v1.ProxyMutationRequest\x1a\x1d.tsm.v1.ProxyMutationResponseB4Z2github.com/wake/tmux-session-menu/api/tsm/v1;tsmv1b\x06proto3"

var (
	file_api_proto_tsm_v1_tsm_proto_rawDescOnce sync.Once
	file_api_proto_tsm_v1_tsm_proto_rawDescData []byte
)

func file_api_proto_tsm_v1_tsm_proto_rawDescGZIP() []byte {
	file_api_proto_tsm_v1_tsm_proto_rawDescOnce.Do(func() {
		file_api_proto_tsm_v1_tsm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_tsm_v1_tsm_proto_rawDesc), len(file_api_proto_tsm_v1_tsm_proto_rawDesc)))
	})
	return file_api_proto_tsm_v1_tsm_proto_rawDescData
}

var file_api_proto_tsm_v1_tsm_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_proto_tsm_v1_tsm_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_api_proto_tsm_v1_tsm_proto_goTypes = []any{
	(SessionStatus)(0),                // 0: tsm.v1.SessionStatus
	(HostStatus)(0),                   // 1: tsm.v1.HostStatus
	(MutationType)(0),                 // 2: tsm.v1.MutationType
	(*Session)(nil),                   // 3: tsm.v1.Session
	(*Group)(nil),                     // 4: tsm.v1.Group
	(*StateSnapshot)(nil),             // 5: tsm.v1.StateSnapshot
	(*HostState)(nil),                 // 6: tsm.v1.HostState
	(*MultiHostSnapshot)(nil),         // 7: tsm.v1.MultiHostSnapshot
	(*ProxyMutationRequest)(nil),      // 8: tsm.v1.ProxyMutationRequest
	(*ProxyMutationResponse)(nil),     // 9: tsm.v1.ProxyMutationResponse
	(*WatchRequest)(nil),              // 10: tsm.v1.WatchRequest
	(*WatchMultiHostRequest)(nil),     // 11: tsm.v1.WatchMultiHostRequest
	(*CreateSessionRequest)(nil),      // 12: tsm.v1.CreateSessionRequest
	(*KillSessionRequest)(nil),        // 13: tsm.v1.KillSessionRequest
	(*RenameSessionRequest)(nil),      // 14: tsm.v1.RenameSessionRequest
	(*RenameGroupRequest)(nil),        // 15: tsm.v1.RenameGroupRequest
	(*CreateGroupRequest)(nil),        // 16: tsm.v1.CreateGroupRequest
	(*MoveSessionRequest)(nil),        // 17: tsm.v1.MoveSessionRequest
	(*ReorderRequest)(nil),            // 18: tsm.v1.ReorderRequest
	(*GroupReorder)(nil),              // 19: tsm.v1.GroupReorder
	(*SessionReorder)(nil),            // 20: tsm.v1.SessionReorder
	(*ToggleCollapseRequest)(nil),     // 21: tsm.v1.ToggleCollapseRequest
	(*DaemonStatusResponse)(nil),      // 22: tsm.v1.DaemonStatusResponse
	(*ConfigValue)(nil),               // 23: tsm.v1.ConfigValue
	(*GetConfigRequest)(nil),          // 24: tsm.v1.GetConfigRequest
	(*GetConfigResponse)(nil),         // 25: tsm.v1.GetConfigResponse
	(*SetConfigRequest)(nil),          // 26: tsm.v1.SetConfigRequest
	(*UploadedFile)(nil),              // 27: tsm.v1.UploadedFile
	(*UploadEvent)(nil),               // 28: tsm.v1.UploadEvent
	(*GetUploadTargetRequest)(nil),    // 29: tsm.v1.GetUploadTargetRequest
	(*GetUploadTargetResponse)(nil),   // 30: tsm.v1.GetUploadTargetResponse
	(*SetUploadModeRequest)(nil),      // 31: tsm.v1.SetUploadModeRequest
	(*ReportUploadResultRequest)(nil), // 32: tsm.v1.ReportUploadResultRequest
	(*timestamppb.Timestamp)(nil),     // 33: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 34: google.protobuf.Empty
}
var file_api_proto_tsm_v1_tsm_proto_depIdxs = []int32{
	33, // 0: tsm.v1.Session.activity:type_name -> google.protobuf.Timestamp
	0,  // 1: tsm.v1.Session.status:type_name -> tsm.v1.SessionStatus
	3,  // 2: tsm.v1.StateSnapshot.sessions:type_name -> tsm.v1.Session
	4,  // 3: tsm.v1.StateSnapshot.groups:type_name -> tsm.v1.Group
	28, // 4: tsm.v1.StateSnapshot.upload_events:type_name -> tsm.v1.UploadEvent
	1,  // 5: tsm.v1.HostState.status:type_name -> tsm.v1.HostStatus
	5,  // 6: tsm.v1.HostState.snapshot:type_name -> tsm.v1.StateSnapshot
	6,  // 7: tsm.v1.MultiHostSnapshot.hosts:type_name -> tsm.v1.HostState
	2,  // 8: tsm.v1.ProxyMutationRequest.type:type_name -> tsm.v1.MutationType
	19, // 9: tsm.v1.ReorderRequest.group:type_name -> tsm.v1.GroupReorder
	20, // 10: tsm.v1.ReorderRequest.session:type_name -> tsm.v1.SessionReorder
	33, // 11: tsm.v1.DaemonStatusResponse.started_at:type_name -> google.protobuf.Timestamp
	23, // 12: tsm.v1.GetConfigResponse.values:type_name -> tsm.v1.ConfigValue
	23, // 13: tsm.v1.SetConfigRequest.values:type_name -> tsm.v1.ConfigValue
	27, // 14: tsm.v1.UploadEvent.files:type_name -> tsm.v1.UploadedFile
	27, // 15: tsm.v1.ReportUploadResultRequest.files:type_name -> tsm.v1.UploadedFile
	10, // 16: tsm.v1.SessionManager.Watch:input_type -> tsm.v1.WatchRequest
	12, // 17: tsm.v1.SessionManager.CreateSession:input_type -> tsm.v1.CreateSessionRequest
	13, // 18: tsm.v1.SessionManager.KillSession:input_type -> tsm.v1.KillSessionRequest
	14, // 19: tsm.v1.SessionManager.RenameSession:input_type -> tsm.v1.RenameSessionRequest
	16, // 20: tsm.v1.SessionManager.CreateGroup:input_type -> tsm.v1.CreateGroupRequest
	15, // 21: tsm.v1.SessionManager.RenameGroup:input_type -> tsm.v1.RenameGroupRequest
	17, // 22: tsm.v1.SessionManager.MoveSession:input_type -> tsm.v1.MoveSessionRequest
	18, // 23: tsm.v1.SessionManager.Reorder:input_type -> tsm.v1.ReorderRequest
	21, // 24: tsm.v1.SessionManager.ToggleCollapse:input_type -> tsm.v1.ToggleCollapseRequest
	34, // 25: tsm.v1.SessionManager.DaemonStatus:input_type -> google.protobuf.Empty
	24, // 26: tsm.v1.SessionManager.GetConfig:input_type -> tsm.v1.GetConfigRequest
	26, // 27: tsm.v1.SessionManager.SetConfig:input_type -> tsm.v1.SetConfigRequest
	29, // 28: tsm.v1.SessionManager.GetUploadTarget:input_type -> tsm.v1.GetUploadTargetRequest
	31, // 29: tsm.v1.SessionManager.SetUploadMode:input_type -> tsm.v1.SetUploadModeRequest
	32, // 30: tsm.v1.SessionManager.ReportUploadResult:input_type -> tsm.v1.ReportUploadResultRequest
	11, // 31: tsm.v1.SessionManager.WatchMultiHost:input_type -> tsm.v1.WatchMultiHostRequest
	8,  // 32: tsm.v1.SessionManager.ProxyMutation:input_type -> tsm.v1.ProxyMutationRequest
	5,  // 33: tsm.v1.SessionManager.Watch:output_type -> tsm.v1.StateSnapshot
	34, // 34: tsm.v1.SessionManager.CreateSession:output_type -> google.protobuf.Empty
	34, // 35: tsm.v1.SessionManager.KillSession:output_type -> google.protobuf.Empty
	34, // 36: tsm.v1.SessionManager.RenameSession:output_type -> google.protobuf.Empty
	34, // 37: tsm.v1.SessionManager.CreateGroup:output_type -> google.protobuf.Empty
	34, // 38: tsm.v1.SessionManager.RenameGroup:output_type -> google.protobuf.Empty
	34, // 39: tsm.v1.SessionManager.MoveSession:output_type -> google.protobuf.Empty
	34, // 40: tsm.v1.SessionManager.Reorder:output_type -> google.protobuf.Empty
	34, // 41: tsm.v1.SessionManager.ToggleCollapse:output_type -> google.protobuf.Empty
	22, // 42: tsm.v1.SessionManager.DaemonStatus:output_type -> tsm.v1.DaemonStatusResponse
	25, // 43: tsm.v1.SessionManager.GetConfig:output_type -> tsm.v1.GetConfigResponse
	34, // 44: tsm.v1.SessionManager.SetConfig:output_type -> google.protobuf.Empty
	30, // 45: tsm.v1.SessionManager.GetUploadTarget:output_type -> tsm.v1.GetUploadTargetResponse
	34, // 46: tsm.v1.SessionManager.SetUploadMode:output_type -> google.protobuf.Empty
	34, // 47: tsm.v1.SessionManager.ReportUploadResult:output_type -> google.protobuf.Empty
	7,  // 48: tsm.v1.SessionManager.WatchMultiHost:output_type -> tsm.v1.MultiHostSnapshot
	9,  // 49: tsm.v1.SessionManager.ProxyMutation:output_type -> tsm.v1.ProxyMutationResponse
	33, // [33:50] is the sub-list for method output_type
	16, // [16:33] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_proto_tsm_v1_tsm_proto_init() }
func file_api_proto_tsm_v1_tsm_proto_init() {
	if File_api_proto_tsm_v1_tsm_proto != nil {
		return
	}
	file_api_proto_tsm_v1_tsm_proto_msgTypes[15].OneofWrappers = []any{
		(*ReorderRequest_Group)(nil),
		(*ReorderRequest_Session)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_tsm_v1_tsm_proto_rawDesc), len(file_api_proto_tsm_v1_tsm_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_tsm_v1_tsm_proto_goTypes,
		DependencyIndexes: file_api_proto_tsm_v1_tsm_proto_depIdxs,
		EnumInfos:         file_api_proto_tsm_v1_tsm_proto_enumTypes,
		MessageInfos:      file_api_proto_tsm_v1_tsm_proto_msgTypes,
	}.Build()
	File_api_proto_tsm_v1_tsm_proto = out.File
	file_api_proto_tsm_v1_tsm_proto_goTypes = nil
	file_api_proto_tsm_v1_tsm_proto_depIdxs = nil
}
