// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/tsm/v1/tsm.proto

package tsmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SessionStatus 對應 tmux.SessionStatus。
type SessionStatus int32

const (
	SessionStatus_SESSION_STATUS_IDLE    SessionStatus = 0
	SessionStatus_SESSION_STATUS_RUNNING SessionStatus = 1
	SessionStatus_SESSION_STATUS_WAITING SessionStatus = 2
	SessionStatus_SESSION_STATUS_ERROR   SessionStatus = 3
)

// Enum value maps for SessionStatus.
var (
	SessionStatus_name = map[int32]string{
		0: "SESSION_STATUS_IDLE",
		1: "SESSION_STATUS_RUNNING",
		2: "SESSION_STATUS_WAITING",
		3: "SESSION_STATUS_ERROR",
	}
	SessionStatus_value = map[string]int32{
		"SESSION_STATUS_IDLE":    0,
		"SESSION_STATUS_RUNNING": 1,
		"SESSION_STATUS_WAITING": 2,
		"SESSION_STATUS_ERROR":   3,
	}
)

func (x SessionStatus) Enum() *SessionStatus {
	p := new(SessionStatus)
	*p = x
	return p
}

func (x SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_tsm_v1_tsm_proto_enumTypes[0].Descriptor()
}

func (SessionStatus) Type() protoreflect.EnumType {
	return &file_api_proto_tsm_v1_tsm_proto_enumTypes[0]
}

func (x SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionStatus.Descriptor instead.
func (SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{0}
}

// Session 對應 tmux.Session。
type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Attached      bool                   `protobuf:"varint,4,opt,name=attached,proto3" json:"attached,omitempty"`
	Activity      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=activity,proto3" json:"activity,omitempty"`
	Status        SessionStatus          `protobuf:"varint,6,opt,name=status,proto3,enum=tsm.v1.SessionStatus" json:"status,omitempty"`
	AiModel       string                 `protobuf:"bytes,7,opt,name=ai_model,json=aiModel,proto3" json:"ai_model,omitempty"`
	AiSummary     string                 `protobuf:"bytes,8,opt,name=ai_summary,json=aiSummary,proto3" json:"ai_summary,omitempty"`
	GroupName     string                 `protobuf:"bytes,9,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	SortOrder     int32                  `protobuf:"varint,10,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	CustomName    string                 `protobuf:"bytes,11,opt,name=custom_name,json=customName,proto3" json:"custom_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Session) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Session) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Session) GetAttached() bool {
	if x != nil {
		return x.Attached
	}
	return false
}

func (x *Session) GetActivity() *timestamppb.Timestamp {
	if x != nil {
		return x.Activity
	}
	return nil
}

func (x *Session) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_IDLE
}

func (x *Session) GetAiModel() string {
	if x != nil {
		return x.AiModel
	}
	return ""
}

func (x *Session) GetAiSummary() string {
	if x != nil {
		return x.AiSummary
	}
	return ""
}

func (x *Session) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *Session) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Session) GetCustomName() string {
	if x != nil {
		return x.CustomName
	}
	return ""
}

// Group 對應 store.Group。
type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SortOrder     int32                  `protobuf:"varint,3,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Collapsed     bool                   `protobuf:"varint,4,opt,name=collapsed,proto3" json:"collapsed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{1}
}

func (x *Group) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Group) GetCollapsed() bool {
	if x != nil {
		return x.Collapsed
	}
	return false
}

// StateSnapshot 是 Watch stream 推送的全量快照。
type StateSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Groups        []*Group               `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateSnapshot) Reset() {
	*x = StateSnapshot{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateSnapshot) ProtoMessage() {}

func (x *StateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateSnapshot.ProtoReflect.Descriptor instead.
func (*StateSnapshot) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{2}
}

func (x *StateSnapshot) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *StateSnapshot) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

// WatchRequest 是 Watch RPC 的請求（目前為空，未來可擴充過濾條件）。
type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{3}
}

// CreateSessionRequest 建立新的 tmux session。
type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSessionRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// KillSessionRequest 刪除指定的 tmux session。
type KillSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillSessionRequest) Reset() {
	*x = KillSessionRequest{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillSessionRequest) ProtoMessage() {}

func (x *KillSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillSessionRequest.ProtoReflect.Descriptor instead.
func (*KillSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{5}
}

func (x *KillSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// RenameSessionRequest 設定 session 的自訂顯示名稱，並可選擇重命名 tmux session。
type RenameSessionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionName    string                 `protobuf:"bytes,1,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	CustomName     string                 `protobuf:"bytes,2,opt,name=custom_name,json=customName,proto3" json:"custom_name,omitempty"`
	NewSessionName string                 `protobuf:"bytes,3,opt,name=new_session_name,json=newSessionName,proto3" json:"new_session_name,omitempty"` // 重命名 tmux session（空 = 不變）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RenameSessionRequest) Reset() {
	*x = RenameSessionRequest{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameSessionRequest) ProtoMessage() {}

func (x *RenameSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameSessionRequest.ProtoReflect.Descriptor instead.
func (*RenameSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{6}
}

func (x *RenameSessionRequest) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

func (x *RenameSessionRequest) GetCustomName() string {
	if x != nil {
		return x.CustomName
	}
	return ""
}

func (x *RenameSessionRequest) GetNewSessionName() string {
	if x != nil {
		return x.NewSessionName
	}
	return ""
}

// RenameGroupRequest 重命名群組。
type RenameGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	NewName       string                 `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameGroupRequest) Reset() {
	*x = RenameGroupRequest{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameGroupRequest) ProtoMessage() {}

func (x *RenameGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameGroupRequest.ProtoReflect.Descriptor instead.
func (*RenameGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{7}
}

func (x *RenameGroupRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *RenameGroupRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

// CreateGroupRequest 建立新的群組。
type CreateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SortOrder     int32                  `protobuf:"varint,2,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{8}
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

// MoveSessionRequest 將 session 移動到指定群組。
type MoveSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionName   string                 `protobuf:"bytes,1,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	SortOrder     int32                  `protobuf:"varint,3,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveSessionRequest) Reset() {
	*x = MoveSessionRequest{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveSessionRequest) ProtoMessage() {}

func (x *MoveSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveSessionRequest.ProtoReflect.Descriptor instead.
func (*MoveSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{9}
}

func (x *MoveSessionRequest) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

func (x *MoveSessionRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *MoveSessionRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

// ReorderRequest 重新排序群組或群組內的 session。
type ReorderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 被排序的對象類型
	//
	// Types that are valid to be assigned to Target:
	//
	//	*ReorderRequest_Group
	//	*ReorderRequest_Session
	Target        isReorderRequest_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReorderRequest) Reset() {
	*x = ReorderRequest{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReorderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReorderRequest) ProtoMessage() {}

func (x *ReorderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReorderRequest.ProtoReflect.Descriptor instead.
func (*ReorderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{10}
}

func (x *ReorderRequest) GetTarget() isReorderRequest_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ReorderRequest) GetGroup() *GroupReorder {
	if x != nil {
		if x, ok := x.Target.(*ReorderRequest_Group); ok {
			return x.Group
		}
	}
	return nil
}

func (x *ReorderRequest) GetSession() *SessionReorder {
	if x != nil {
		if x, ok := x.Target.(*ReorderRequest_Session); ok {
			return x.Session
		}
	}
	return nil
}

type isReorderRequest_Target interface {
	isReorderRequest_Target()
}

type ReorderRequest_Group struct {
	Group *GroupReorder `protobuf:"bytes,1,opt,name=group,proto3,oneof"`
}

type ReorderRequest_Session struct {
	Session *SessionReorder `protobuf:"bytes,2,opt,name=session,proto3,oneof"`
}

func (*ReorderRequest_Group) isReorderRequest_Target() {}

func (*ReorderRequest_Session) isReorderRequest_Target() {}

type GroupReorder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	NewSortOrder  int32                  `protobuf:"varint,2,opt,name=new_sort_order,json=newSortOrder,proto3" json:"new_sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupReorder) Reset() {
	*x = GroupReorder{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupReorder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupReorder) ProtoMessage() {}

func (x *GroupReorder) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupReorder.ProtoReflect.Descriptor instead.
func (*GroupReorder) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{11}
}

func (x *GroupReorder) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupReorder) GetNewSortOrder() int32 {
	if x != nil {
		return x.NewSortOrder
	}
	return 0
}

type SessionReorder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionName   string                 `protobuf:"bytes,1,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	NewSortOrder  int32                  `protobuf:"varint,3,opt,name=new_sort_order,json=newSortOrder,proto3" json:"new_sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionReorder) Reset() {
	*x = SessionReorder{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionReorder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionReorder) ProtoMessage() {}

func (x *SessionReorder) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionReorder.ProtoReflect.Descriptor instead.
func (*SessionReorder) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{12}
}

func (x *SessionReorder) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

func (x *SessionReorder) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *SessionReorder) GetNewSortOrder() int32 {
	if x != nil {
		return x.NewSortOrder
	}
	return 0
}

// ToggleCollapseRequest 切換群組的展開/收合狀態。
type ToggleCollapseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleCollapseRequest) Reset() {
	*x = ToggleCollapseRequest{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleCollapseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleCollapseRequest) ProtoMessage() {}

func (x *ToggleCollapseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleCollapseRequest.ProtoReflect.Descriptor instead.
func (*ToggleCollapseRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{13}
}

func (x *ToggleCollapseRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

// DaemonStatusResponse 回傳 daemon 的狀態資訊。
type DaemonStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	WatcherCount  int32                  `protobuf:"varint,3,opt,name=watcher_count,json=watcherCount,proto3" json:"watcher_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonStatusResponse) Reset() {
	*x = DaemonStatusResponse{}
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonStatusResponse) ProtoMessage() {}

func (x *DaemonStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_tsm_v1_tsm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonStatusResponse.ProtoReflect.Descriptor instead.
func (*DaemonStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_tsm_v1_tsm_proto_rawDescGZIP(), []int{14}
}

func (x *DaemonStatusResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *DaemonStatusResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *DaemonStatusResponse) GetWatcherCount() int32 {
	if x != nil {
		return x.WatcherCount
	}
	return 0
}

var File_api_proto_tsm_v1_tsm_proto protoreflect.FileDescriptor

const file_api_proto_tsm_v1_tsm_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/tsm/v1/tsm.proto\x12\x06tsm.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdd\x02\n" +
	"\aSession\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1a\n" +
	"\battached\x18\x04 \x01(\bR\battached\x126\n" +
	"\bactivity\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bactivity\x12-\n" +
	"\x06status\x18\x06 \x01(\x0e2\x15.tsm.v1.SessionStatusR\x06status\x12\x19\n" +
	"\bai_model\x18\a \x01(\tR\aaiModel\x12\x1d\n" +
	"\n" +
	"ai_summary\x18\b \x01(\tR\taiSummary\x12\x1d\n" +
	"\n" +
	"group_name\x18\t \x01(\tR\tgroupName\x12\x1d\n" +
	"\n" +
	"sort_order\x18\n" +
	" \x01(\x05R\tsortOrder\x12\x1f\n" +
	"\vcustom_name\x18\v \x01(\tR\n" +
	"customName\"h\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x03 \x01(\x05R\tsortOrder\x12\x1c\n" +
	"\tcollapsed\x18\x04 \x01(\bR\tcollapsed\"c\n" +
	"\rStateSnapshot\x12+\n" +
	"\bsessions\x18\x01 \x03(\v2\x0f.tsm.v1.SessionR\bsessions\x12%\n" +
	"\x06groups\x18\x02 \x03(\v2\r.tsm.v1.GroupR\x06groups\"\x0e\n" +
	"\fWatchRequest\">\n" +
	"\x14CreateSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"(\n" +
	"\x12KillSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x84\x01\n" +
	"\x14RenameSessionRequest\x12!\n" +
	"\fsession_name\x18\x01 \x01(\tR\vsessionName\x12\x1f\n" +
	"\vcustom_name\x18\x02 \x01(\tR\n" +
	"customName\x12(\n" +
	"\x10new_session_name\x18\x03 \x01(\tR\x0enewSessionName\"J\n" +
	"\x12RenameGroupRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x19\n" +
	"\bnew_name\x18\x02 \x01(\tR\anewName\"G\n" +
	"\x12CreateGroupRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x02 \x01(\x05R\tsortOrder\"q\n" +
	"\x12MoveSessionRequest\x12!\n" +
	"\fsession_name\x18\x01 \x01(\tR\vsessionName\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x03 \x01(\x05R\tsortOrder\"|\n" +
	"\x0eReorderRequest\x12,\n" +
	"\x05group\x18\x01 \x01(\v2\x14.tsm.v1.GroupReorderH\x00R\x05group\x122\n" +
	"\asession\x18\x02 \x01(\v2\x16.tsm.v1.SessionReorderH\x00R\asessionB\b\n" +
	"\x06target\"O\n" +
	"\fGroupReorder\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12$\n" +
	"\x0enew_sort_order\x18\x02 \x01(\x05R\fnewSortOrder\"t\n" +
	"\x0eSessionReorder\x12!\n" +
	"\fsession_name\x18\x01 \x01(\tR\vsessionName\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\x12$\n" +
	"\x0enew_sort_order\x18\x03 \x01(\x05R\fnewSortOrder\"2\n" +
	"\x15ToggleCollapseRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\"\x88\x01\n" +
	"\x14DaemonStatusResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x129\n" +
	"\n" +
	"started_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12#\n" +
	"\rwatcher_count\x18\x03 \x01(\x05R\fwatcherCount*z\n" +
	"\rSessionStatus\x12\x17\n" +
	"\x13SESSION_STATUS_IDLE\x10\x00\x12\x1a\n" +
	"\x16SESSION_STATUS_RUNNING\x10\x01\x12\x1a\n" +
	"\x16SESSION_STATUS_WAITING\x10\x02\x12\x18\n" +
	"\x14SESSION_STATUS_ERROR\x10\x032\xac\x05\n" +
	"\x0eSessionManager\x126\n" +
	"\x05Watch\x12\x14.tsm.v1.WatchRequest\x1a\x15.tsm.v1.StateSnapshot0\x01\x12E\n" +
	"\rCreateSession\x12\x1c.tsm.v1.CreateSessionRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\vKillSession\x12\x1a.tsm.v1.KillSessionRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\rRenameSession\x12\x1c.tsm.v1.RenameSessionRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\vCreateGroup\x12\x1a.tsm.v1.CreateGroupRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\vRenameGroup\x12\x1a.tsm.v1.RenameGroupRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\vMoveSession\x12\x1a.tsm.v1.MoveSessionRequest\x1a\x16.google.protobuf.Empty\x129\n" +
	"\aReorder\x12\x16.tsm.v1.ReorderRequest\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\x0eToggleCollapse\x12\x1d.tsm.v1.ToggleCollapseRequest\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\fDaemonStatus\x12\x16.google.protobuf.Empty\x1a\x1c.tsm.v1.DaemonStatusResponseB4Z2github.com/wake/tmux-session-menu/api/tsm/v1;tsmv1b\x06proto3"

var (
	file_api_proto_tsm_v1_tsm_proto_rawDescOnce sync.Once
	file_api_proto_tsm_v1_tsm_proto_rawDescData []byte
)

func file_api_proto_tsm_v1_tsm_proto_rawDescGZIP() []byte {
	file_api_proto_tsm_v1_tsm_proto_rawDescOnce.Do(func() {
		file_api_proto_tsm_v1_tsm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_tsm_v1_tsm_proto_rawDesc), len(file_api_proto_tsm_v1_tsm_proto_rawDesc)))
	})
	return file_api_proto_tsm_v1_tsm_proto_rawDescData
}

var file_api_proto_tsm_v1_tsm_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_tsm_v1_tsm_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_proto_tsm_v1_tsm_proto_goTypes = []any{
	(SessionStatus)(0),            // 0: tsm.v1.SessionStatus
	(*Session)(nil),               // 1: tsm.v1.Session
	(*Group)(nil),                 // 2: tsm.v1.Group
	(*StateSnapshot)(nil),         // 3: tsm.v1.StateSnapshot
	(*WatchRequest)(nil),          // 4: tsm.v1.WatchRequest
	(*CreateSessionRequest)(nil),  // 5: tsm.v1.CreateSessionRequest
	(*KillSessionRequest)(nil),    // 6: tsm.v1.KillSessionRequest
	(*RenameSessionRequest)(nil),  // 7: tsm.v1.RenameSessionRequest
	(*RenameGroupRequest)(nil),    // 8: tsm.v1.RenameGroupRequest
	(*CreateGroupRequest)(nil),    // 9: tsm.v1.CreateGroupRequest
	(*MoveSessionRequest)(nil),    // 10: tsm.v1.MoveSessionRequest
	(*ReorderRequest)(nil),        // 11: tsm.v1.ReorderRequest
	(*GroupReorder)(nil),          // 12: tsm.v1.GroupReorder
	(*SessionReorder)(nil),        // 13: tsm.v1.SessionReorder
	(*ToggleCollapseRequest)(nil), // 14: tsm.v1.ToggleCollapseRequest
	(*DaemonStatusResponse)(nil),  // 15: tsm.v1.DaemonStatusResponse
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 17: google.protobuf.Empty
}
var file_api_proto_tsm_v1_tsm_proto_depIdxs = []int32{
	16, // 0: tsm.v1.Session.activity:type_name -> google.protobuf.Timestamp
	0,  // 1: tsm.v1.Session.status:type_name -> tsm.v1.SessionStatus
	1,  // 2: tsm.v1.StateSnapshot.sessions:type_name -> tsm.v1.Session
	2,  // 3: tsm.v1.StateSnapshot.groups:type_name -> tsm.v1.Group
	12, // 4: tsm.v1.ReorderRequest.group:type_name -> tsm.v1.GroupReorder
	13, // 5: tsm.v1.ReorderRequest.session:type_name -> tsm.v1.SessionReorder
	16, // 6: tsm.v1.DaemonStatusResponse.started_at:type_name -> google.protobuf.Timestamp
	4,  // 7: tsm.v1.SessionManager.Watch:input_type -> tsm.v1.WatchRequest
	5,  // 8: tsm.v1.SessionManager.CreateSession:input_type -> tsm.v1.CreateSessionRequest
	6,  // 9: tsm.v1.SessionManager.KillSession:input_type -> tsm.v1.KillSessionRequest
	7,  // 10: tsm.v1.SessionManager.RenameSession:input_type -> tsm.v1.RenameSessionRequest
	9,  // 11: tsm.v1.SessionManager.CreateGroup:input_type -> tsm.v1.CreateGroupRequest
	8,  // 12: tsm.v1.SessionManager.RenameGroup:input_type -> tsm.v1.RenameGroupRequest
	10, // 13: tsm.v1.SessionManager.MoveSession:input_type -> tsm.v1.MoveSessionRequest
	11, // 14: tsm.v1.SessionManager.Reorder:input_type -> tsm.v1.ReorderRequest
	14, // 15: tsm.v1.SessionManager.ToggleCollapse:input_type -> tsm.v1.ToggleCollapseRequest
	17, // 16: tsm.v1.SessionManager.DaemonStatus:input_type -> google.protobuf.Empty
	3,  // 17: tsm.v1.SessionManager.Watch:output_type -> tsm.v1.StateSnapshot
	17, // 18: tsm.v1.SessionManager.CreateSession:output_type -> google.protobuf.Empty
	17, // 19: tsm.v1.SessionManager.KillSession:output_type -> google.protobuf.Empty
	17, // 20: tsm.v1.SessionManager.RenameSession:output_type -> google.protobuf.Empty
	17, // 21: tsm.v1.SessionManager.CreateGroup:output_type -> google.protobuf.Empty
	17, // 22: tsm.v1.SessionManager.RenameGroup:output_type -> google.protobuf.Empty
	17, // 23: tsm.v1.SessionManager.MoveSession:output_type -> google.protobuf.Empty
	17, // 24: tsm.v1.SessionManager.Reorder:output_type -> google.protobuf.Empty
	17, // 25: tsm.v1.SessionManager.ToggleCollapse:output_type -> google.protobuf.Empty
	15, // 26: tsm.v1.SessionManager.DaemonStatus:output_type -> tsm.v1.DaemonStatusResponse
	17, // [17:27] is the sub-list for method output_type
	7,  // [7:17] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_tsm_v1_tsm_proto_init() }
func file_api_proto_tsm_v1_tsm_proto_init() {
	if File_api_proto_tsm_v1_tsm_proto != nil {
		return
	}
	file_api_proto_tsm_v1_tsm_proto_msgTypes[10].OneofWrappers = []any{
		(*ReorderRequest_Group)(nil),
		(*ReorderRequest_Session)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_tsm_v1_tsm_proto_rawDesc), len(file_api_proto_tsm_v1_tsm_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_tsm_v1_tsm_proto_goTypes,
		DependencyIndexes: file_api_proto_tsm_v1_tsm_proto_depIdxs,
		EnumInfos:         file_api_proto_tsm_v1_tsm_proto_enumTypes,
		MessageInfos:      file_api_proto_tsm_v1_tsm_proto_msgTypes,
	}.Build()
	File_api_proto_tsm_v1_tsm_proto = out.File
	file_api_proto_tsm_v1_tsm_proto_goTypes = nil
	file_api_proto_tsm_v1_tsm_proto_depIdxs = nil
}
