// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api/proto/tsm/v1/tsm.proto

package tsmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SessionManager_Watch_FullMethodName          = "/tsm.v1.SessionManager/Watch"
	SessionManager_CreateSession_FullMethodName  = "/tsm.v1.SessionManager/CreateSession"
	SessionManager_KillSession_FullMethodName    = "/tsm.v1.SessionManager/KillSession"
	SessionManager_RenameSession_FullMethodName  = "/tsm.v1.SessionManager/RenameSession"
	SessionManager_CreateGroup_FullMethodName    = "/tsm.v1.SessionManager/CreateGroup"
	SessionManager_RenameGroup_FullMethodName    = "/tsm.v1.SessionManager/RenameGroup"
	SessionManager_MoveSession_FullMethodName    = "/tsm.v1.SessionManager/MoveSession"
	SessionManager_Reorder_FullMethodName        = "/tsm.v1.SessionManager/Reorder"
	SessionManager_ToggleCollapse_FullMethodName = "/tsm.v1.SessionManager/ToggleCollapse"
	SessionManager_DaemonStatus_FullMethodName   = "/tsm.v1.SessionManager/DaemonStatus"
	SessionManager_GetConfig_FullMethodName      = "/tsm.v1.SessionManager/GetConfig"
	SessionManager_SetConfig_FullMethodName      = "/tsm.v1.SessionManager/SetConfig"
)

// SessionManagerClient is the client API for SessionManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SessionManager 是 tsm daemon 的核心 gRPC service。
type SessionManagerClient interface {
	// Watch 建立 server streaming，持續推送 StateSnapshot。
	// 連線後立即推送一次初始快照，之後每當狀態變更時推送差異快照。
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StateSnapshot], error)
	// 操作型 unary RPCs — 操作完成後變更透過 Watch stream 自動推送。
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	KillSession(ctx context.Context, in *KillSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RenameSession(ctx context.Context, in *RenameSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RenameGroup(ctx context.Context, in *RenameGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	MoveSession(ctx context.Context, in *MoveSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Reorder(ctx context.Context, in *ReorderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ToggleCollapse(ctx context.Context, in *ToggleCollapseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// DaemonStatus 回傳 daemon 的狀態資訊。
	DaemonStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DaemonStatusResponse, error)
	// GetConfig 取得 daemon 所在主機的設定。
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	// SetConfig 更新 daemon 所在主機的設定。
	SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type sessionManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionManagerClient(cc grpc.ClientConnInterface) SessionManagerClient {
	return &sessionManagerClient{cc}
}

func (c *sessionManagerClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StateSnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SessionManager_ServiceDesc.Streams[0], SessionManager_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, StateSnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SessionManager_WatchClient = grpc.ServerStreamingClient[StateSnapshot]

func (c *sessionManagerClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SessionManager_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) KillSession(ctx context.Context, in *KillSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SessionManager_KillSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) RenameSession(ctx context.Context, in *RenameSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SessionManager_RenameSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SessionManager_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) RenameGroup(ctx context.Context, in *RenameGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SessionManager_RenameGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) MoveSession(ctx context.Context, in *MoveSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SessionManager_MoveSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) Reorder(ctx context.Context, in *ReorderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SessionManager_Reorder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) ToggleCollapse(ctx context.Context, in *ToggleCollapseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SessionManager_ToggleCollapse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) DaemonStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DaemonStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DaemonStatusResponse)
	err := c.cc.Invoke(ctx, SessionManager_DaemonStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, SessionManager_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SessionManager_SetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionManagerServer is the server API for SessionManager service.
// All implementations must embed UnimplementedSessionManagerServer
// for forward compatibility.
//
// SessionManager 是 tsm daemon 的核心 gRPC service。
type SessionManagerServer interface {
	// Watch 建立 server streaming，持續推送 StateSnapshot。
	// 連線後立即推送一次初始快照，之後每當狀態變更時推送差異快照。
	Watch(*WatchRequest, grpc.ServerStreamingServer[StateSnapshot]) error
	// 操作型 unary RPCs — 操作完成後變更透過 Watch stream 自動推送。
	CreateSession(context.Context, *CreateSessionRequest) (*emptypb.Empty, error)
	KillSession(context.Context, *KillSessionRequest) (*emptypb.Empty, error)
	RenameSession(context.Context, *RenameSessionRequest) (*emptypb.Empty, error)
	CreateGroup(context.Context, *CreateGroupRequest) (*emptypb.Empty, error)
	RenameGroup(context.Context, *RenameGroupRequest) (*emptypb.Empty, error)
	MoveSession(context.Context, *MoveSessionRequest) (*emptypb.Empty, error)
	Reorder(context.Context, *ReorderRequest) (*emptypb.Empty, error)
	ToggleCollapse(context.Context, *ToggleCollapseRequest) (*emptypb.Empty, error)
	// DaemonStatus 回傳 daemon 的狀態資訊。
	DaemonStatus(context.Context, *emptypb.Empty) (*DaemonStatusResponse, error)
	// GetConfig 取得 daemon 所在主機的設定。
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	// SetConfig 更新 daemon 所在主機的設定。
	SetConfig(context.Context, *SetConfigRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedSessionManagerServer()
}

// UnimplementedSessionManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionManagerServer struct{}

func (UnimplementedSessionManagerServer) Watch(*WatchRequest, grpc.ServerStreamingServer[StateSnapshot]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedSessionManagerServer) CreateSession(context.Context, *CreateSessionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedSessionManagerServer) KillSession(context.Context, *KillSessionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method KillSession not implemented")
}
func (UnimplementedSessionManagerServer) RenameSession(context.Context, *RenameSessionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameSession not implemented")
}
func (UnimplementedSessionManagerServer) CreateGroup(context.Context, *CreateGroupRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedSessionManagerServer) RenameGroup(context.Context, *RenameGroupRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameGroup not implemented")
}
func (UnimplementedSessionManagerServer) MoveSession(context.Context, *MoveSessionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveSession not implemented")
}
func (UnimplementedSessionManagerServer) Reorder(context.Context, *ReorderRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Reorder not implemented")
}
func (UnimplementedSessionManagerServer) ToggleCollapse(context.Context, *ToggleCollapseRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ToggleCollapse not implemented")
}
func (UnimplementedSessionManagerServer) DaemonStatus(context.Context, *emptypb.Empty) (*DaemonStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DaemonStatus not implemented")
}
func (UnimplementedSessionManagerServer) GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedSessionManagerServer) SetConfig(context.Context, *SetConfigRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetConfig not implemented")
}
func (UnimplementedSessionManagerServer) mustEmbedUnimplementedSessionManagerServer() {}
func (UnimplementedSessionManagerServer) testEmbeddedByValue()                        {}

// UnsafeSessionManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionManagerServer will
// result in compilation errors.
type UnsafeSessionManagerServer interface {
	mustEmbedUnimplementedSessionManagerServer()
}

func RegisterSessionManagerServer(s grpc.ServiceRegistrar, srv SessionManagerServer) {
	// If the following call panics, it indicates UnimplementedSessionManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SessionManager_ServiceDesc, srv)
}

func _SessionManager_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SessionManagerServer).Watch(m, &grpc.GenericServerStream[WatchRequest, StateSnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SessionManager_WatchServer = grpc.ServerStreamingServer[StateSnapshot]

func _SessionManager_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_KillSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).KillSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_KillSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).KillSession(ctx, req.(*KillSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_RenameSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).RenameSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_RenameSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).RenameSession(ctx, req.(*RenameSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_RenameGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).RenameGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_RenameGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).RenameGroup(ctx, req.(*RenameGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_MoveSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).MoveSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_MoveSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).MoveSession(ctx, req.(*MoveSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_Reorder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReorderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).Reorder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_Reorder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).Reorder(ctx, req.(*ReorderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_ToggleCollapse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleCollapseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).ToggleCollapse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_ToggleCollapse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).ToggleCollapse(ctx, req.(*ToggleCollapseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_DaemonStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).DaemonStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_DaemonStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).DaemonStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_SetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).SetConfig(ctx, req.(*SetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionManager_ServiceDesc is the grpc.ServiceDesc for SessionManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tsm.v1.SessionManager",
	HandlerType: (*SessionManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _SessionManager_CreateSession_Handler,
		},
		{
			MethodName: "KillSession",
			Handler:    _SessionManager_KillSession_Handler,
		},
		{
			MethodName: "RenameSession",
			Handler:    _SessionManager_RenameSession_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _SessionManager_CreateGroup_Handler,
		},
		{
			MethodName: "RenameGroup",
			Handler:    _SessionManager_RenameGroup_Handler,
		},
		{
			MethodName: "MoveSession",
			Handler:    _SessionManager_MoveSession_Handler,
		},
		{
			MethodName: "Reorder",
			Handler:    _SessionManager_Reorder_Handler,
		},
		{
			MethodName: "ToggleCollapse",
			Handler:    _SessionManager_ToggleCollapse_Handler,
		},
		{
			MethodName: "DaemonStatus",
			Handler:    _SessionManager_DaemonStatus_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _SessionManager_GetConfig_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _SessionManager_SetConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _SessionManager_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/tsm/v1/tsm.proto",
}
