// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: tsm/v1/tsm.proto

package tsmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SessionManager_Watch_FullMethodName               = "/tsm.v1.SessionManager/Watch"
	SessionManager_CreateSession_FullMethodName       = "/tsm.v1.SessionManager/CreateSession"
	SessionManager_KillSession_FullMethodName         = "/tsm.v1.SessionManager/KillSession"
	SessionManager_RenameSession_FullMethodName       = "/tsm.v1.SessionManager/RenameSession"
	SessionManager_CreateGroup_FullMethodName         = "/tsm.v1.SessionManager/CreateGroup"
	SessionManager_RenameGroup_FullMethodName         = "/tsm.v1.SessionManager/RenameGroup"
	SessionManager_MoveSession_FullMethodName         = "/tsm.v1.SessionManager/MoveSession"
	SessionManager_Reorder_FullMethodName             = "/tsm.v1.SessionManager/Reorder"
	SessionManager_ToggleCollapse_FullMethodName      = "/tsm.v1.SessionManager/ToggleCollapse"
	SessionManager_DaemonStatus_FullMethodName        = "/tsm.v1.SessionManager/DaemonStatus"
	SessionManager_GetConfig_FullMethodName           = "/tsm.v1.SessionManager/GetConfig"
	SessionManager_SetConfig_FullMethodName           = "/tsm.v1.SessionManager/SetConfig"
	SessionManager_GetUploadTarget_FullMethodName     = "/tsm.v1.SessionManager/GetUploadTarget"
	SessionManager_SetUploadMode_FullMethodName       = "/tsm.v1.SessionManager/SetUploadMode"
	SessionManager_ReportUploadResult_FullMethodName  = "/tsm.v1.SessionManager/ReportUploadResult"
	SessionManager_WatchMultiHost_FullMethodName      = "/tsm.v1.SessionManager/WatchMultiHost"
	SessionManager_ProxyMutation_FullMethodName       = "/tsm.v1.SessionManager/ProxyMutation"
	SessionManager_RequestAttach_FullMethodName       = "/tsm.v1.SessionManager/RequestAttach"
	SessionManager_TakePendingAttach_FullMethodName   = "/tsm.v1.SessionManager/TakePendingAttach"
	SessionManager_CancelPendingAttach_FullMethodName = "/tsm.v1.SessionManager/CancelPendingAttach"
	SessionManager_GetHostsConfig_FullMethodName      = "/tsm.v1.SessionManager/GetHostsConfig"
	SessionManager_UpdateHostConfig_FullMethodName    = "/tsm.v1.SessionManager/UpdateHostConfig"
)

// SessionManagerClient is the client API for SessionManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SessionManager 是 tsm daemon 的核心 gRPC service。
type SessionManagerClient interface {
	// Watch 建立 server streaming，持續推送 StateSnapshot。
	// 連線後立即推送一次初始快照，之後每當狀態變更時推送差異快照。
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StateSnapshot], error)
	// 操作型 unary RPCs — 操作完成後變更透過 Watch stream 自動推送。
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	KillSession(ctx context.Context, in *KillSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RenameSession(ctx context.Context, in *RenameSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RenameGroup(ctx context.Context, in *RenameGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	MoveSession(ctx context.Context, in *MoveSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Reorder(ctx context.Context, in *ReorderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ToggleCollapse(ctx context.Context, in *ToggleCollapseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// DaemonStatus 回傳 daemon 的狀態資訊。
	DaemonStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DaemonStatusResponse, error)
	// GetConfig 取得 daemon 所在主機的設定。
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	// SetConfig 更新 daemon 所在主機的設定。
	SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetUploadTarget 查詢當前 focused session 的上傳目標。
	GetUploadTarget(ctx context.Context, in *GetUploadTargetRequest, opts ...grpc.CallOption) (*GetUploadTargetResponse, error)
	// SetUploadMode 設定上傳模式開關（TUI 控制）。
	SetUploadMode(ctx context.Context, in *SetUploadModeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ReportUploadResult 回報上傳結果（coprocess 呼叫）。
	ReportUploadResult(ctx context.Context, in *ReportUploadResultRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// WatchMultiHost 回傳多主機聚合快照 stream（hub 模式專用）。
	WatchMultiHost(ctx context.Context, in *WatchMultiHostRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MultiHostSnapshot], error)
	// ProxyMutation 將操作代理到目標主機的 daemon（hub 模式專用）。
	ProxyMutation(ctx context.Context, in *ProxyMutationRequest, opts ...grpc.CallOption) (*ProxyMutationResponse, error)
	// RequestAttach 由 spoke 發送，請求 hub 切換到指定主機的 session（hub-socket 模式專用）。
	RequestAttach(ctx context.Context, in *RequestAttachRequest, opts ...grpc.CallOption) (*RequestAttachResponse, error)
	// TakePendingAttach 由 hub 呼叫，取得並清除 pending attach（read-and-clear 語意）。
	TakePendingAttach(ctx context.Context, in *TakePendingAttachRequest, opts ...grpc.CallOption) (*TakePendingAttachResponse, error)
	// CancelPendingAttach 取消尚未消費的 pending attach（popup 異常關閉時呼叫）。
	CancelPendingAttach(ctx context.Context, in *CancelPendingAttachRequest, opts ...grpc.CallOption) (*CancelPendingAttachResponse, error)
	// GetHostsConfig 取得 daemon 所在主機的 hosts 設定。
	GetHostsConfig(ctx context.Context, in *GetHostsConfigRequest, opts ...grpc.CallOption) (*GetHostsConfigResponse, error)
	// UpdateHostConfig 更新 daemon 所在主機的 hosts 設定。
	UpdateHostConfig(ctx context.Context, in *UpdateHostConfigRequest, opts ...grpc.CallOption) (*UpdateHostConfigResponse, error)
}

type sessionManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionManagerClient(cc grpc.ClientConnInterface) SessionManagerClient {
	return &sessionManagerClient{cc}
}

func (c *sessionManagerClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StateSnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SessionManager_ServiceDesc.Streams[0], SessionManager_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, StateSnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SessionManager_WatchClient = grpc.ServerStreamingClient[StateSnapshot]

func (c *sessionManagerClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SessionManager_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) KillSession(ctx context.Context, in *KillSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SessionManager_KillSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) RenameSession(ctx context.Context, in *RenameSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SessionManager_RenameSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SessionManager_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) RenameGroup(ctx context.Context, in *RenameGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SessionManager_RenameGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) MoveSession(ctx context.Context, in *MoveSessionRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SessionManager_MoveSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) Reorder(ctx context.Context, in *ReorderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SessionManager_Reorder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) ToggleCollapse(ctx context.Context, in *ToggleCollapseRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SessionManager_ToggleCollapse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) DaemonStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DaemonStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DaemonStatusResponse)
	err := c.cc.Invoke(ctx, SessionManager_DaemonStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, SessionManager_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SessionManager_SetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) GetUploadTarget(ctx context.Context, in *GetUploadTargetRequest, opts ...grpc.CallOption) (*GetUploadTargetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUploadTargetResponse)
	err := c.cc.Invoke(ctx, SessionManager_GetUploadTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) SetUploadMode(ctx context.Context, in *SetUploadModeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SessionManager_SetUploadMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) ReportUploadResult(ctx context.Context, in *ReportUploadResultRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SessionManager_ReportUploadResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) WatchMultiHost(ctx context.Context, in *WatchMultiHostRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MultiHostSnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SessionManager_ServiceDesc.Streams[1], SessionManager_WatchMultiHost_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchMultiHostRequest, MultiHostSnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SessionManager_WatchMultiHostClient = grpc.ServerStreamingClient[MultiHostSnapshot]

func (c *sessionManagerClient) ProxyMutation(ctx context.Context, in *ProxyMutationRequest, opts ...grpc.CallOption) (*ProxyMutationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProxyMutationResponse)
	err := c.cc.Invoke(ctx, SessionManager_ProxyMutation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) RequestAttach(ctx context.Context, in *RequestAttachRequest, opts ...grpc.CallOption) (*RequestAttachResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestAttachResponse)
	err := c.cc.Invoke(ctx, SessionManager_RequestAttach_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) TakePendingAttach(ctx context.Context, in *TakePendingAttachRequest, opts ...grpc.CallOption) (*TakePendingAttachResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TakePendingAttachResponse)
	err := c.cc.Invoke(ctx, SessionManager_TakePendingAttach_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) CancelPendingAttach(ctx context.Context, in *CancelPendingAttachRequest, opts ...grpc.CallOption) (*CancelPendingAttachResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelPendingAttachResponse)
	err := c.cc.Invoke(ctx, SessionManager_CancelPendingAttach_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) GetHostsConfig(ctx context.Context, in *GetHostsConfigRequest, opts ...grpc.CallOption) (*GetHostsConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHostsConfigResponse)
	err := c.cc.Invoke(ctx, SessionManager_GetHostsConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sessionManagerClient) UpdateHostConfig(ctx context.Context, in *UpdateHostConfigRequest, opts ...grpc.CallOption) (*UpdateHostConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateHostConfigResponse)
	err := c.cc.Invoke(ctx, SessionManager_UpdateHostConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionManagerServer is the server API for SessionManager service.
// All implementations must embed UnimplementedSessionManagerServer
// for forward compatibility.
//
// SessionManager 是 tsm daemon 的核心 gRPC service。
type SessionManagerServer interface {
	// Watch 建立 server streaming，持續推送 StateSnapshot。
	// 連線後立即推送一次初始快照，之後每當狀態變更時推送差異快照。
	Watch(*WatchRequest, grpc.ServerStreamingServer[StateSnapshot]) error
	// 操作型 unary RPCs — 操作完成後變更透過 Watch stream 自動推送。
	CreateSession(context.Context, *CreateSessionRequest) (*emptypb.Empty, error)
	KillSession(context.Context, *KillSessionRequest) (*emptypb.Empty, error)
	RenameSession(context.Context, *RenameSessionRequest) (*emptypb.Empty, error)
	CreateGroup(context.Context, *CreateGroupRequest) (*emptypb.Empty, error)
	RenameGroup(context.Context, *RenameGroupRequest) (*emptypb.Empty, error)
	MoveSession(context.Context, *MoveSessionRequest) (*emptypb.Empty, error)
	Reorder(context.Context, *ReorderRequest) (*emptypb.Empty, error)
	ToggleCollapse(context.Context, *ToggleCollapseRequest) (*emptypb.Empty, error)
	// DaemonStatus 回傳 daemon 的狀態資訊。
	DaemonStatus(context.Context, *emptypb.Empty) (*DaemonStatusResponse, error)
	// GetConfig 取得 daemon 所在主機的設定。
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	// SetConfig 更新 daemon 所在主機的設定。
	SetConfig(context.Context, *SetConfigRequest) (*emptypb.Empty, error)
	// GetUploadTarget 查詢當前 focused session 的上傳目標。
	GetUploadTarget(context.Context, *GetUploadTargetRequest) (*GetUploadTargetResponse, error)
	// SetUploadMode 設定上傳模式開關（TUI 控制）。
	SetUploadMode(context.Context, *SetUploadModeRequest) (*emptypb.Empty, error)
	// ReportUploadResult 回報上傳結果（coprocess 呼叫）。
	ReportUploadResult(context.Context, *ReportUploadResultRequest) (*emptypb.Empty, error)
	// WatchMultiHost 回傳多主機聚合快照 stream（hub 模式專用）。
	WatchMultiHost(*WatchMultiHostRequest, grpc.ServerStreamingServer[MultiHostSnapshot]) error
	// ProxyMutation 將操作代理到目標主機的 daemon（hub 模式專用）。
	ProxyMutation(context.Context, *ProxyMutationRequest) (*ProxyMutationResponse, error)
	// RequestAttach 由 spoke 發送，請求 hub 切換到指定主機的 session（hub-socket 模式專用）。
	RequestAttach(context.Context, *RequestAttachRequest) (*RequestAttachResponse, error)
	// TakePendingAttach 由 hub 呼叫，取得並清除 pending attach（read-and-clear 語意）。
	TakePendingAttach(context.Context, *TakePendingAttachRequest) (*TakePendingAttachResponse, error)
	// CancelPendingAttach 取消尚未消費的 pending attach（popup 異常關閉時呼叫）。
	CancelPendingAttach(context.Context, *CancelPendingAttachRequest) (*CancelPendingAttachResponse, error)
	// GetHostsConfig 取得 daemon 所在主機的 hosts 設定。
	GetHostsConfig(context.Context, *GetHostsConfigRequest) (*GetHostsConfigResponse, error)
	// UpdateHostConfig 更新 daemon 所在主機的 hosts 設定。
	UpdateHostConfig(context.Context, *UpdateHostConfigRequest) (*UpdateHostConfigResponse, error)
	mustEmbedUnimplementedSessionManagerServer()
}

// UnimplementedSessionManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionManagerServer struct{}

func (UnimplementedSessionManagerServer) Watch(*WatchRequest, grpc.ServerStreamingServer[StateSnapshot]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedSessionManagerServer) CreateSession(context.Context, *CreateSessionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedSessionManagerServer) KillSession(context.Context, *KillSessionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method KillSession not implemented")
}
func (UnimplementedSessionManagerServer) RenameSession(context.Context, *RenameSessionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameSession not implemented")
}
func (UnimplementedSessionManagerServer) CreateGroup(context.Context, *CreateGroupRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedSessionManagerServer) RenameGroup(context.Context, *RenameGroupRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameGroup not implemented")
}
func (UnimplementedSessionManagerServer) MoveSession(context.Context, *MoveSessionRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MoveSession not implemented")
}
func (UnimplementedSessionManagerServer) Reorder(context.Context, *ReorderRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Reorder not implemented")
}
func (UnimplementedSessionManagerServer) ToggleCollapse(context.Context, *ToggleCollapseRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ToggleCollapse not implemented")
}
func (UnimplementedSessionManagerServer) DaemonStatus(context.Context, *emptypb.Empty) (*DaemonStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DaemonStatus not implemented")
}
func (UnimplementedSessionManagerServer) GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedSessionManagerServer) SetConfig(context.Context, *SetConfigRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetConfig not implemented")
}
func (UnimplementedSessionManagerServer) GetUploadTarget(context.Context, *GetUploadTargetRequest) (*GetUploadTargetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUploadTarget not implemented")
}
func (UnimplementedSessionManagerServer) SetUploadMode(context.Context, *SetUploadModeRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetUploadMode not implemented")
}
func (UnimplementedSessionManagerServer) ReportUploadResult(context.Context, *ReportUploadResultRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportUploadResult not implemented")
}
func (UnimplementedSessionManagerServer) WatchMultiHost(*WatchMultiHostRequest, grpc.ServerStreamingServer[MultiHostSnapshot]) error {
	return status.Error(codes.Unimplemented, "method WatchMultiHost not implemented")
}
func (UnimplementedSessionManagerServer) ProxyMutation(context.Context, *ProxyMutationRequest) (*ProxyMutationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProxyMutation not implemented")
}
func (UnimplementedSessionManagerServer) RequestAttach(context.Context, *RequestAttachRequest) (*RequestAttachResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestAttach not implemented")
}
func (UnimplementedSessionManagerServer) TakePendingAttach(context.Context, *TakePendingAttachRequest) (*TakePendingAttachResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TakePendingAttach not implemented")
}
func (UnimplementedSessionManagerServer) CancelPendingAttach(context.Context, *CancelPendingAttachRequest) (*CancelPendingAttachResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelPendingAttach not implemented")
}
func (UnimplementedSessionManagerServer) GetHostsConfig(context.Context, *GetHostsConfigRequest) (*GetHostsConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHostsConfig not implemented")
}
func (UnimplementedSessionManagerServer) UpdateHostConfig(context.Context, *UpdateHostConfigRequest) (*UpdateHostConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateHostConfig not implemented")
}
func (UnimplementedSessionManagerServer) mustEmbedUnimplementedSessionManagerServer() {}
func (UnimplementedSessionManagerServer) testEmbeddedByValue()                        {}

// UnsafeSessionManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionManagerServer will
// result in compilation errors.
type UnsafeSessionManagerServer interface {
	mustEmbedUnimplementedSessionManagerServer()
}

func RegisterSessionManagerServer(s grpc.ServiceRegistrar, srv SessionManagerServer) {
	// If the following call panics, it indicates UnimplementedSessionManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SessionManager_ServiceDesc, srv)
}

func _SessionManager_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SessionManagerServer).Watch(m, &grpc.GenericServerStream[WatchRequest, StateSnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SessionManager_WatchServer = grpc.ServerStreamingServer[StateSnapshot]

func _SessionManager_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_KillSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).KillSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_KillSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).KillSession(ctx, req.(*KillSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_RenameSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).RenameSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_RenameSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).RenameSession(ctx, req.(*RenameSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_RenameGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).RenameGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_RenameGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).RenameGroup(ctx, req.(*RenameGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_MoveSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).MoveSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_MoveSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).MoveSession(ctx, req.(*MoveSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_Reorder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReorderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).Reorder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_Reorder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).Reorder(ctx, req.(*ReorderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_ToggleCollapse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleCollapseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).ToggleCollapse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_ToggleCollapse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).ToggleCollapse(ctx, req.(*ToggleCollapseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_DaemonStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).DaemonStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_DaemonStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).DaemonStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_SetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).SetConfig(ctx, req.(*SetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_GetUploadTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUploadTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).GetUploadTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_GetUploadTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).GetUploadTarget(ctx, req.(*GetUploadTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_SetUploadMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUploadModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).SetUploadMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_SetUploadMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).SetUploadMode(ctx, req.(*SetUploadModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_ReportUploadResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportUploadResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).ReportUploadResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_ReportUploadResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).ReportUploadResult(ctx, req.(*ReportUploadResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_WatchMultiHost_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchMultiHostRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SessionManagerServer).WatchMultiHost(m, &grpc.GenericServerStream[WatchMultiHostRequest, MultiHostSnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SessionManager_WatchMultiHostServer = grpc.ServerStreamingServer[MultiHostSnapshot]

func _SessionManager_ProxyMutation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProxyMutationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).ProxyMutation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_ProxyMutation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).ProxyMutation(ctx, req.(*ProxyMutationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_RequestAttach_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestAttachRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).RequestAttach(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_RequestAttach_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).RequestAttach(ctx, req.(*RequestAttachRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_TakePendingAttach_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TakePendingAttachRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).TakePendingAttach(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_TakePendingAttach_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).TakePendingAttach(ctx, req.(*TakePendingAttachRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_CancelPendingAttach_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelPendingAttachRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).CancelPendingAttach(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_CancelPendingAttach_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).CancelPendingAttach(ctx, req.(*CancelPendingAttachRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_GetHostsConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostsConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).GetHostsConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_GetHostsConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).GetHostsConfig(ctx, req.(*GetHostsConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SessionManager_UpdateHostConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHostConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionManagerServer).UpdateHostConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionManager_UpdateHostConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionManagerServer).UpdateHostConfig(ctx, req.(*UpdateHostConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionManager_ServiceDesc is the grpc.ServiceDesc for SessionManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tsm.v1.SessionManager",
	HandlerType: (*SessionManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _SessionManager_CreateSession_Handler,
		},
		{
			MethodName: "KillSession",
			Handler:    _SessionManager_KillSession_Handler,
		},
		{
			MethodName: "RenameSession",
			Handler:    _SessionManager_RenameSession_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _SessionManager_CreateGroup_Handler,
		},
		{
			MethodName: "RenameGroup",
			Handler:    _SessionManager_RenameGroup_Handler,
		},
		{
			MethodName: "MoveSession",
			Handler:    _SessionManager_MoveSession_Handler,
		},
		{
			MethodName: "Reorder",
			Handler:    _SessionManager_Reorder_Handler,
		},
		{
			MethodName: "ToggleCollapse",
			Handler:    _SessionManager_ToggleCollapse_Handler,
		},
		{
			MethodName: "DaemonStatus",
			Handler:    _SessionManager_DaemonStatus_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _SessionManager_GetConfig_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _SessionManager_SetConfig_Handler,
		},
		{
			MethodName: "GetUploadTarget",
			Handler:    _SessionManager_GetUploadTarget_Handler,
		},
		{
			MethodName: "SetUploadMode",
			Handler:    _SessionManager_SetUploadMode_Handler,
		},
		{
			MethodName: "ReportUploadResult",
			Handler:    _SessionManager_ReportUploadResult_Handler,
		},
		{
			MethodName: "ProxyMutation",
			Handler:    _SessionManager_ProxyMutation_Handler,
		},
		{
			MethodName: "RequestAttach",
			Handler:    _SessionManager_RequestAttach_Handler,
		},
		{
			MethodName: "TakePendingAttach",
			Handler:    _SessionManager_TakePendingAttach_Handler,
		},
		{
			MethodName: "CancelPendingAttach",
			Handler:    _SessionManager_CancelPendingAttach_Handler,
		},
		{
			MethodName: "GetHostsConfig",
			Handler:    _SessionManager_GetHostsConfig_Handler,
		},
		{
			MethodName: "UpdateHostConfig",
			Handler:    _SessionManager_UpdateHostConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _SessionManager_Watch_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchMultiHost",
			Handler:       _SessionManager_WatchMultiHost_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tsm/v1/tsm.proto",
}
